### ISSUE TITLE
An error occurred while running code

### ISSUE THREAD

**Issue by cxq1** [ucas-vg/PointTinyBenchmark#72]
When I execute the code [cmd 0], I find a problem, as shown below. I found that the implementation of evaluation seems to be missing in the code. Could you provide it? I would appreciate it if you could.
![image](https://user-images.githubusercontent.com/35260648/191772062-0bc00652-4267-432b-bac7-beb3fb1b0521.png)
![image](https://user-images.githubusercontent.com/35260648/191772136-1c24070e-661f-4895-b2ab-bcc7a830c09d.png)
![image](https://user-images.githubusercontent.com/35260648/191772153-737dd1cf-d9ae-4306-a181-4af5e6b50669.png)

python=3.7 cuda=11.6 memory size=40G A100

**Comment by yinglang** [comment]
Hi, thanks for this report. this is due to some files([TOV_mmdetection/mmdet/models/detectors/base.py](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/mmdet/models/detectors/base.py) and [TOV_mmdetection/mmdet/models/detectors/single_stage.py](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/mmdet/models/detectors/single_stage.py)) are not updated.
These problem should been solved by replacing the files with the latest code.

**Comment by cxq1** [comment]
Thank you for your reply

**Comment by cxq1** [comment]
![NFKW2KAPPOI~MPDBX (3Q{I](https://user-images.githubusercontent.com/35260648/191884885-6f14ced9-cd18-4d0b-b6a2-0a063428d8d4.png)
It's still the same problem

**Comment by yinglang** [comment]
Thanks for feedback. The problem can be solved by add **kwargs in the functions‘ defination just like [this](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/mmdet/models/dense_heads/base_dense_head.py#L61)

**Comment by cxq1** [comment]
![1663910344277](https://user-images.githubusercontent.com/35260648/191896446-257656e6-1f92-432d-8109-45fa816a316b.png)
Excuse me again, the problem is still there. And I can't find the function "simple_test_bboxes" where is defined.

**Comment by yinglang** [comment]
Sorry for that, I forget there is another function defination should be change, you can check [there](https://github.com/ucas-vg/PointTinyBenchmark/blob/master/TOV_mmdetection/mmdet/models/dense_heads/dense_test_mixins.py#L15)

**Comment by cxq1** [comment]
![1663916561573](https://user-images.githubusercontent.com/35260648/191907923-a2953dff-d851-44a0-8134-a9a11f120721.png)
Excuse me again. There seems to be some code missing in this file eval_hooks.py

**Comment by yinglang** [comment]
Thanks again. This problem have been solved by replace the TOV_mmdetection/mmdet/apis/train.py as the [commit](https://github.com/ucas-vg/PointTinyBenchmark/commit/db85cc161f0747517d081b0ca8430e60450511ec) told.

**Comment by yinglang** [comment]
I have updatd the [eval_hooks.py](https://github.com/ucas-vg/P2BNet/blob/main/TOV_mmdetection/mmdet/core/evaluation/eval_hooks.py). And eval_hooks.py in P2B should work too.

**Comment by cxq1** [comment]
![1663979362508](https://user-images.githubusercontent.com/35260648/192072173-e8712a24-f106-4398-a111-2610a025271e.png)
![1663979451060](https://user-images.githubusercontent.com/35260648/192072228-c8eb87a2-445b-415f-a11d-db8a517a77c9.png)
Excuse me again,I don't know why this error occurs
![1663979540431](https://user-images.githubusercontent.com/35260648/192072298-f5e1c1fe-c930-46d3-a067-522bd6214fae.png)
![1663979600055](https://user-images.githubusercontent.com/35260648/192072334-23409d74-809c-4b88-9813-aabc61d39f0e.png)

**Comment by yinglang** [comment]
Does the problem still exists?

**Comment by cxq1** [comment]
![1664071090969](https://user-images.githubusercontent.com/35260648/192125004-73de777b-7303-41fb-9cc1-718b8d7eb311.png)
The problem remains

**Comment by yinglang** [comment]
> ![1663979362508](https://user-images.githubusercontent.com/35260648/192072173-e8712a24-f106-4398-a111-2610a025271e.png) ![1663979451060](https://user-images.githubusercontent.com/35260648/192072228-c8eb87a2-445b-415f-a11d-db8a517a77c9.png) Excuse me again,I don't know why this error occurs ![1663979540431](https://user-images.githubusercontent.com/35260648/192072298-f5e1c1fe-c930-46d3-a067-522bd6214fae.png) ![1663979600055](https://user-images.githubusercontent.com/35260648/192072334-23409d74-809c-4b88-9813-aabc61d39f0e.png)

Does this problem still exists?

**Comment by yinglang** [comment]
> ![1664071090969](https://user-images.githubusercontent.com/35260648/192125004-73de777b-7303-41fb-9cc1-718b8d7eb311.png) The problem remains

Could you check the result file that is rright format of coco detection result?
![image](https://user-images.githubusercontent.com/9081484/192127918-816fa925-c898-4ead-ad8a-8401eae3d07a.png)

**Comment by cxq1** [comment]
Thanks, the problem is mostly solved
